version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-sphinx-theme"
    assignees:
      - "pyansys-ci-bot"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build(pip)"
    groups:
      pip-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 10 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    assignees:
      - "pyansys-ci-bot"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build(actions)"
    groups:
      action-deps:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    cooldown:
      default-days: 7 # semver-* options are not applicable for pre-commit
      exclude:
        - "ansys/pre-commit-hooks/*"
    labels:
      - "maintenance"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "build(pre-commit)"
    groups:
      pre-commit-hooks-deps:
        patterns:
          - "*"

